// Produktdaten - später vom Server
// Hilfsfunktionen für Produktfilterung
function getNewProducts() {
  return PRODUCTS.filter(p => p.isNew);
}

function getPopularProducts() {
  return PRODUCTS.filter(p => p.featured);
}

function getAllProducts() {
  return PRODUCTS;
}

function renderProductsFromArray(containerId, products, detailed = false) {
  const container = document.getElementById(containerId);
  if (!container) return;
  
  container.innerHTML = products.map(product => `
    <article class="product-card" data-id="${product.id}">
      <div class="product-image" style="background-image: linear-gradient(45deg, ${product.gradient[0]}, ${product.gradient[1]});">
        <img src="${product.image}" alt="${product.name}" loading="lazy">
        ${product.isNew ? '<div class="product-badge new">Neu</div>' : ''}
      </div>
      <div class="product-info">
        <h3>${product.name}</h3>
        <p>${product.description}</p>
        ${detailed ? `
          <div class="product-details">
            <p class="small">${product.details}</p>
            <ul class="features">
              ${product.features.map(f => `<li>${f}</li>`).join('')}
            </ul>
            <div class="product-meta">
              <span class="size">${product.size}</span>
              <span class="servings">${product.servings} Portionen</span>
            </div>
          </div>
        ` : ''}
        <div class="product-footer">
          <div class="price">${product.price.toFixed(2)}€</div>
          <button class="button" onclick="addToCart('${product.id}')">In den Warenkorb</button>
        </div>
      </div>
    </article>
  `).join('');
}

// Produktkategorien:
// basics - Klassische Geschmacksrichtungen
// vitality - Energie und Vitalität
// wellness - Gesundheit und Wohlbefinden
// relax - Entspannung
// focus - Konzentration
// immunity - Immunsystem
// exotic - Besondere Geschmackserlebnisse
// seasonal - Saisonale Editionen

const PRODUCTS = [
  // === MEHR BASICS ===
  {
    id: 'tropical-mix',
    name: 'Tropical Mix',
    description: 'Tropischer Fruchtmix für Urlaubsfeeling.',
    details: 'Ananas, Mango und Papaya mit einem Hauch Kokos',
    category: 'basics',
    price: 13.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FFB347/ffffff?text=Tropical+Mix',
    gradient: ['#FFB347', '#FFDA47'],
    featured: false,
    isNew: false
  },
  {
    id: 'strawberry-kiwi',
    name: 'Strawberry Kiwi',
    description: 'Fruchtige Kombination aus Erdbeere und Kiwi.',
    details: 'Saftige Erdbeeren mit erfrischender Kiwi',
    category: 'basics',
    price: 13.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit Vitamin C', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FF69B4/ffffff?text=Strawberry+Kiwi',
    gradient: ['#FF69B4', '#98FB98'],
    featured: false,
    isNew: false
  },
  {
    id: 'grape-elderflower',
    name: 'Grape & Elderflower',
    description: 'Elegante Mischung aus Traube und Holunderblüte.',
    details: 'Weiße Trauben verfeinert mit floraler Holunderblüte',
    category: 'basics',
    price: 13.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/DDA0DD/ffffff?text=Grape+Elder',
    gradient: ['#DDA0DD', '#E6E6FA'],
    featured: false,
    isNew: false
  },
  {
    id: 'watermelon-mint',
    name: 'Watermelon Mint',
    description: 'Erfrischende Wassermelone mit Minze.',
    details: 'Saftige Wassermelone mit frischer Minznote',
    category: 'basics',
    price: 13.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FF6B6B/ffffff?text=Watermelon',
    gradient: ['#FF6B6B', '#98FB98'],
    featured: false,
    isNew: false
  },
  {
    id: 'blood-orange',
    name: 'Blood Orange',
    description: 'Intensive Blutorange mit leichter Bitternote.',
    details: 'Sizilianische Blutorangen mit charakteristischer Färbung',
    category: 'basics',
    price: 13.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Reich an Antioxidantien', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FF4500/ffffff?text=Blood+Orange',
    gradient: ['#FF4500', '#FF6347'],
    featured: false,
    isNew: false
  },
  // === BASICS ===
  {
    id: 'classic-lemon',
    name: 'Classic Lemon',
    description: 'Der Klassiker: Erfrischende Zitrone, perfekt für jeden Tag.',
    details: 'Natürliches Zitronenaroma mit ausgewogener Säure und feiner Süße aus Stevia',
    category: 'basics',
    price: 12.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit Vitamin C', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FFF44F/ffffff?text=Classic+Lemon',
    gradient: ['#FFF44F', '#FFDB58'],
    featured: true,
    isNew: false
  },
  {
    id: 'fresh-orange',
    name: 'Fresh Orange',
    description: 'Sonnengereifter Orangengeschmack für den perfekten Start.',
    details: 'Natürliches Orangenaroma mit einem Hauch von Mandarine',
    category: 'basics',
    price: 12.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Reich an Vitamin C', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FFA500/ffffff?text=Fresh+Orange',
    gradient: ['#FFA500', '#FFD700'],
    featured: false,
    isNew: false
  },
  {
    id: 'wild-berry',
    name: 'Wild Berry',
    description: 'Intensive Beerenmischung aus Waldfrüchten.',
    details: 'Kombination aus Himbeeren, Brombeeren und schwarzen Johannisbeeren',
    category: 'basics',
    price: 13.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Reich an Antioxidantien', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/8B0000/ffffff?text=Wild+Berry',
    gradient: ['#8B0000', '#FF69B4'],
    featured: false,
    isNew: false
  },
  {
    id: 'green-apple',
    name: 'Green Apple',
    description: 'Erfrischend spritziger Apfelgeschmack.',
    details: 'Frischer grüner Apfel mit leichter Säure',
    category: 'basics',
    price: 12.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit Vitamin C', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/90EE90/ffffff?text=Green+Apple',
    gradient: ['#90EE90', '#98FB98'],
    featured: false,
    isNew: false
  },
  {
    id: 'peach-passion',
    name: 'Peach Passion',
    description: 'Süße Pfirsiche mit exotischer Passionsfrucht.',
    details: 'Saftige Pfirsiche verfeinert mit tropischer Passionsfrucht',
    category: 'basics',
    price: 13.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FFDAB9/ffffff?text=Peach+Passion',
    gradient: ['#FFDAB9', '#FFA07A'],
    featured: false,
    isNew: false
  },
  {
    id: 'cucumber-lime',
    name: 'Cucumber Lime',
    description: 'Erfrischende Gurke mit spritziger Limette.',
    details: 'Erfrischende Gurkennote mit Limette und Minze',
    category: 'basics',
    price: 13.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Natürliche Aromen', 'Erfrischend', 'Vegan'],
    image: 'https://placehold.co/400x400/90EE90/ffffff?text=Cucumber+Lime',
    gradient: ['#90EE90', '#98FB98'],
    featured: false,
    isNew: false
  },
  {
    id: 'pomegranate-berry',
    name: 'Pomegranate Berry',
    description: 'Granatapfel mit gemischten Beeren.',
    details: 'Granatapfel kombiniert mit Himbeeren und Brombeeren',
    category: 'basics',
    price: 14.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Reich an Antioxidantien', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/C71585/ffffff?text=Pomegranate',
    gradient: ['#C71585', '#FF69B4'],
    featured: false,
    isNew: false
  },
  {
    id: 'berry-boost',
    name: 'Berry Boost',
    description: 'Natürliche Energie aus Beeren und Superfoods.',
    details: 'Belebende Mischung aus Goji-Beeren, Acai und Himbeeren, angereichert mit B-Vitaminen aus Quinoa',
    category: 'vitality',
    price: 14.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit B-Vitaminen', 'Reich an Antioxidantien', 'Vegan'],
    image: 'https://placehold.co/400x400/FF4D92/ffffff?text=Berry+Boost',
    gradient: ['#FF4D92', '#FFB86B'],
    featured: true,
    isNew: true
  },
  {
    id: 'mint-matcha',
    name: 'Mint Matcha',
    description: 'Erfrischender Matcha-Drink mit Minze für natürliche Fokussierung.',
    details: 'Premium Matcha aus Japan mit erfrischender Minze und L-Theanin für sanfte Energie',
    category: 'focus',
    price: 16.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Reich an L-Theanin', 'Natürliches Koffein', 'Vegan'],
    image: 'https://placehold.co/400x400/90EE90/ffffff?text=Mint+Matcha',
    gradient: ['#90EE90', '#4AB3FF'],
    featured: true,
    isNew: false
  },
  // === EXOTIC BLENDS ===
  {
    id: 'dragon-fruit-dream',
    name: 'Dragon Fruit Dream',
    description: 'Exotischer Mix mit Drachenfrucht und Litschi.',
    details: 'Tropische Kombination aus Drachenfrucht, Litschi und einem Hauch Rosenblüten',
    category: 'exotic',
    price: 15.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Exotische Früchte', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FF69B4/ffffff?text=Dragon+Fruit',
    gradient: ['#FF69B4', '#FFB6C1'],
    featured: true,
    isNew: true
  },
  {
    id: 'mango-chili',
    name: 'Mango Chili',
    description: 'Süße Mango trifft auf sanfte Chilinote.',
    details: 'Reife Alphonso-Mango mit feiner Cayenneschärfe und Limette',
    category: 'exotic',
    price: 14.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit Cayenne', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FFD700/ffffff?text=Mango+Chili',
    gradient: ['#FFD700', '#FF4500'],
    featured: false,
    isNew: true
  },
  {
    id: 'sakura-plum',
    name: 'Sakura Plum',
    description: 'Japanische Kirschblüte mit saftiger Pflaume.',
    details: 'Inspiriert von japanischen Frühlingsfesten: Kirschblüte, Pflaume und grüner Tee',
    category: 'exotic',
    price: 15.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit Matcha', 'Natürliche Aromen', 'Vegan'],
    image: 'https://placehold.co/400x400/FFB7C5/ffffff?text=Sakura+Plum',
    gradient: ['#FFB7C5', '#DDA0DD'],
    featured: false,
    isNew: true
  },
  // === SEASONAL EDITIONS ===
  {
    id: 'winter-punch',
    name: 'Winter Punch',
    description: 'Wärmender Gewürzpunsch für kalte Tage.',
    details: 'Zimt, Nelken, Orange und Apfel mit wärmender Gewürzmischung',
    category: 'seasonal',
    price: 14.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Wärmende Gewürze', 'Limited Edition', 'Vegan'],
    image: 'https://placehold.co/400x400/8B4513/ffffff?text=Winter+Punch',
    gradient: ['#8B4513', '#D2691E'],
    featured: false,
    isNew: true
  },
  {
    id: 'summer-mojito',
    name: 'Summer Mojito',
    description: 'Alkoholfreier Mojito-Style Drink mit frischer Minze.',
    details: 'Erfrischende Kombination aus Limette, Minze und Rum-Aroma',
    category: 'seasonal',
    price: 14.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Alkoholfrei', 'Limited Edition', 'Vegan'],
    image: 'https://placehold.co/400x400/98FF98/ffffff?text=Summer+Mojito',
    gradient: ['#98FF98', '#00FF7F'],
    featured: true,
    isNew: true
  },
  // === IMMUNITY BOOSTERS ===
  {
    id: 'elderberry-zinc',
    name: 'Elderberry Zinc',
    description: 'Immunstärkender Holunderbeeren-Drink mit Zink.',
    details: 'Schwarzer Holunder, Zink und Vitamin C für das Immunsystem',
    category: 'immunity',
    price: 16.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit Zink', 'Immunstärkend', 'Vegan'],
    image: 'https://placehold.co/400x400/4B0082/ffffff?text=Elderberry',
    gradient: ['#4B0082', '#8B008B'],
    featured: false,
    isNew: false
  },
  {
    id: 'ginger-lemon',
    name: 'Ginger Lemon',
    description: 'Klassische Ingwer-Zitronen Kombination.',
    details: 'Scharfer Ingwer mit Zitrone und Honiggeschmack',
    category: 'immunity',
    price: 14.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit Ingwer', 'Vitamin C', 'Vegan'],
    image: 'https://placehold.co/400x400/FFD700/ffffff?text=Ginger+Lemon',
    gradient: ['#FFD700', '#FFA07A'],
    featured: false,
    isNew: false
  },
  // === FOCUS & PERFORMANCE ===
  {
    id: 'brain-boost-blueberry',
    name: 'Brain Boost Blueberry',
    description: 'Konzentrationsfördernder Drink mit Heidelbeeren.',
    details: 'Wilde Heidelbeeren mit Lion\'s Mane und Ginkgo für mentale Leistung',
    category: 'focus',
    price: 17.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit Nootropics', 'Brain Food', 'Vegan'],
    image: 'https://placehold.co/400x400/00008B/ffffff?text=Brain+Boost',
    gradient: ['#00008B', '#4169E1'],
    featured: false,
    isNew: true
  },
  {
    id: 'focus-coffee',
    name: 'Focus Coffee',
    description: 'Cold Brew Style Kaffeedrink mit L-Theanin.',
    details: 'Kaltgebrühter Arabica-Kaffee mit L-Theanin für fokussierte Energie',
    category: 'focus',
    price: 16.99,
    size: '400g',
    servings: 20,
    features: ['Ohne Zucker', 'Mit L-Theanin', 'Cold Brew Style', 'Vegan'],
    image: 'https://placehold.co/400x400/8B4513/ffffff?text=Focus+Coffee',
    gradient: ['#8B4513', '#A0522D'],
    featured: true,
    isNew: false
  },
  // === RELAX & UNWIND ===
  // === NEUE PRODUKTE ===
{
  id: 'lemon-ginger-twist',
  name: 'Lemon Ginger Twist',
  description: 'Erfrischende Zitrone mit leichtem Ingwer-Kick.',
  details: 'Frische Zitronen mit einem Hauch Ingwer für den Extra-Kick',
  category: 'basics',
  price: 13.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Natürliche Aromen', 'Vegan'],
  image: 'https://placehold.co/400x400/FFFACD/ffffff?text=Lemon+Ginger',
  gradient: ['#FFFACD', '#FFD700'],
  featured: false,
  isNew: true
},
{
  id: 'raspberry-lemonade',
  name: 'Raspberry Lemonade',
  description: 'Fruchtig-säuerliche Himbeer-Limonade.',
  details: 'Saftige Himbeeren kombiniert mit frischer Zitrone',
  category: 'basics',
  price: 13.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Natürliche Aromen', 'Vegan'],
  image: 'https://placehold.co/400x400/FF69B4/ffffff?text=Raspberry+Lemonade',
  gradient: ['#FF69B4', '#FFF44F'],
  featured: false,
  isNew: true
},
{
  id: 'blueberry-citrus',
  name: 'Blueberry Citrus',
  description: 'Beerenfrische trifft Zitruskick.',
  details: 'Blaubeeren mit einer Mischung aus Orange und Limette',
  category: 'basics',
  price: 13.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Antioxidantienreich'],
  image: 'https://placehold.co/400x400/8A2BE2/ffffff?text=Blueberry+Citrus',
  gradient: ['#8A2BE2', '#FFD700'],
  featured: false,
  isNew: true
},
{
  id: 'tropical-pineapple',
  name: 'Tropical Pineapple',
  description: 'Saftige Ananas mit exotischem Flair.',
  details: 'Reife Ananas kombiniert mit einem Hauch Kokos',
  category: 'basics',
  price: 13.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Natürliche Aromen'],
  image: 'https://placehold.co/400x400/FFD700/ffffff?text=Tropical+Pineapple',
  gradient: ['#FFD700', '#FFA500'],
  featured: false,
  isNew: true
},
{
  id: 'kiwi-melon',
  name: 'Kiwi Melon',
  description: 'Frischer Kiwi-Melonensaft für heiße Tage.',
  details: 'Grüne Kiwi trifft auf saftige Honigmelone',
  category: 'basics',
  price: 13.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Erfrischend'],
  image: 'https://placehold.co/400x400/32CD32/ffffff?text=Kiwi+Melon',
  gradient: ['#32CD32', '#98FB98'],
  featured: false,
  isNew: true
},

// === VITALITY ===
{
  id: 'acai-energy',
  name: 'Acai Energy',
  description: 'Superfood-Energie aus Acai-Beeren.',
  details: 'Acai, Goji und Blaubeeren mit B-Vitaminen',
  category: 'vitality',
  price: 15.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Reich an Antioxidantien', 'Vegan'],
  image: 'https://placehold.co/400x400/4B0082/ffffff?text=Acai+Energy',
  gradient: ['#4B0082', '#8A2BE2'],
  featured: false,
  isNew: true
},
{
  id: 'goji-berry-boost',
  name: 'Goji Berry Boost',
  description: 'Beerenkraft für Energie & Fokus.',
  details: 'Goji-Beeren, Himbeeren und Granatapfel für den Kick',
  category: 'vitality',
  price: 15.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Reich an Antioxidantien', 'Vegan'],
  image: 'https://placehold.co/400x400/FF4500/ffffff?text=Goji+Berry',
  gradient: ['#FF4500', '#FF6347'],
  featured: false,
  isNew: true
},
{
  id: 'spirulina-citrus',
  name: 'Spirulina Citrus',
  description: 'Grüne Power kombiniert mit Zitrus.',
  details: 'Spirulina, Limette, Orange – voller Energie',
  category: 'vitality',
  price: 16.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Reich an Chlorophyll'],
  image: 'https://placehold.co/400x400/00FF7F/ffffff?text=Spirulina+Citrus',
  gradient: ['#00FF7F', '#32CD32'],
  featured: false,
  isNew: true
},
{
  id: 'green-detox',
  name: 'Green Detox',
  description: 'Erfrischender Detox-Drink mit Supergreens.',
  details: 'Grüner Tee, Spirulina, Moringa für Balance und Energie',
  category: 'vitality',
  price: 16.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Entgiftend'],
  image: 'https://placehold.co/400x400/3CB371/ffffff?text=Green+Detox',
  gradient: ['#3CB371', '#98FB98'],
  featured: false,
  isNew: true
},
{
  id: 'mango-papaya-charge',
  name: 'Mango Papaya Charge',
  description: 'Tropischer Energie-Boost mit Mango & Papaya.',
  details: 'Saftige Mango trifft auf süße Papaya',
  category: 'vitality',
  price: 15.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Natürliche Aromen'],
  image: 'https://placehold.co/400x400/FFD700/ffffff?text=Mango+Papaya',
  gradient: ['#FFD700', '#FFA500'],
  featured: false,
  isNew: true
},

// === WELLNESS ===
{
  id: 'ginger-apple-tonic',
  name: 'Ginger Apple Tonic',
  description: 'Erfrischender Apfel-Ingwer Drink.',
  details: 'Apfel trifft auf würzigen Ingwer für Balance und Vitalität',
  category: 'wellness',
  price: 14.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Mit Ingwer'],
  image: 'https://placehold.co/400x400/FF8C00/ffffff?text=Ginger+Apple',
  gradient: ['#FF8C00', '#FFA500'],
  featured: false,
  isNew: true
},
{
  id: 'lemon-matcha-vital',
  name: 'Lemon Matcha Vital',
  description: 'Belebender Matcha-Drink mit Zitrone.',
  details: 'Grüner Tee aus Japan mit frischer Zitrone für Energie und Fokus',
  category: 'wellness',
  price: 16.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Reich an Antioxidantien'],
  image: 'https://placehold.co/400x400/90EE90/ffffff?text=Lemon+Matcha',
  gradient: ['#90EE90', '#32CD32'],
  featured: false,
  isNew: true
},
{
  id: 'aloe-mint-refresh',
  name: 'Aloe Mint Refresh',
  description: 'Frisch & leicht: Aloe Vera trifft Minze.',
  details: 'Aloe Vera, Minze und Limette für erfrischende Balance',
  category: 'wellness',
  price: 15.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Erfrischend'],
  image: 'https://placehold.co/400x400/98FB98/ffffff?text=Aloe+Mint',
  gradient: ['#98FB98', '#00FA9A'],
  featured: false,
  isNew: true
},

// === RELAX ===
{
  id: 'chamomile-peach',
  name: 'Chamomile Peach',
  description: 'Sanfte Entspannung mit Pfirsich und Kamille.',
  details: 'Kamille, Pfirsich und Melisse für ruhige Momente',
  category: 'relax',
  price: 14.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Entspannend'],
  image: 'https://placehold.co/400x400/FFDAB9/ffffff?text=Chamomile+Peach',
  gradient: ['#FFDAB9', '#FFE4B5'],
  featured: false,
  isNew: true
},
{
  id: 'lavender-honeydew',
  name: 'Lavender Honeydew',
  description: 'Sanfte Lavendel-Note trifft süße Melone.',
  details: 'Lavendel und Honigmelone für einen ruhigen Abend',
  category: 'relax',
  price: 15.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Entspannend'],
  image: 'https://placehold.co/400x400/E6E6FA/ffffff?text=Lavender+Honeydew',
  gradient: ['#E6E6FA', '#D8BFD8'],
  featured: false,
  isNew: true
},
{
  id: 'vanilla-blueberry-calm',
  name: 'Vanilla Blueberry Calm',
  description: 'Beruhigender Drink mit Vanille und Blaubeeren.',
  details: 'Vanille, Blaubeeren und Kamille für entspannte Momente',
  category: 'relax',
  price: 15.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Beruhigend'],
  image: 'https://placehold.co/400x400/8A2BE2/ffffff?text=Vanilla+Blueberry',
  gradient: ['#8A2BE2', '#E6E6FA'],
  featured: false,
  isNew: true
},
{
  id: 'melon-mint-breeze',
  name: 'Melon Mint Breeze',
  description: 'Frischer Drink für Sommerabende.',
  details: 'Honigmelone, Minze und Limette für erfrischende Entspannung',
  category: 'relax',
  price: 14.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Erfrischend'],
  image: 'https://placehold.co/400x400/98FB98/ffffff?text=Melon+Mint',
  gradient: ['#98FB98', '#00FA9A'],
  featured: false,
  isNew: true
},
{
  id: 'passionfruit-chill',
  name: 'Passionfruit Chill',
  description: 'Exotische Passionsfrucht für Ruhe & Balance.',
  details: 'Passionsfrucht, Hibiskus und Melisse für Entspannung',
  category: 'relax',
  price: 15.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Entspannend'],
  image: 'https://placehold.co/400x400/FFB347/ffffff?text=Passionfruit+Chill',
  gradient: ['#FFB347', '#FFD700'],
  featured: false,
  isNew: true
},

// === FOCUS ===
{
  id: 'ginkgo-berry-focus',
  name: 'Ginkgo Berry Focus',
  description: 'Konzentrationsdrink mit Beeren und Ginkgo.',
  details: 'Heidelbeeren und Ginkgo für klare Gedanken',
  category: 'focus',
  price: 16.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Brain Food'],
  image: 'https://placehold.co/400x400/4B0082/ffffff?text=Ginkgo+Berry',
  gradient: ['#4B0082', '#8A2BE2'],
  featured: false,
  isNew: true
},
{
  id: 'lemon-basil-clarity',
  name: 'Lemon Basil Clarity',
  description: 'Zitronen-Basilikum Drink für klare Gedanken.',
  details: 'Frische Zitrone trifft auf Basilikum für Fokus und Wachheit',
  category: 'focus',
  price: 16.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Erfrischend'],
  image: 'https://placehold.co/400x400/FFF44F/ffffff?text=Lemon+Basil',
  gradient: ['#FFF44F', '#ADFF2F'],
  featured: false,
  isNew: true
},
{
  id: 'green-tea-citrus-focus',
  name: 'Green Tea Citrus Focus',
  description: 'Grüner Tee mit Zitrus für mentalen Kick.',
  details: 'Grüner Tee, Limette und Orange für Wachheit',
  category: 'focus',
  price: 16.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Natürliches Koffein'],
  image: 'https://placehold.co/400x400/32CD32/ffffff?text=Green+Tea+Citrus',
  gradient: ['#32CD32', '#98FB98'],
  featured: false,
  isNew: true
},
{
  id: 'rosemary-lemon-sharp',
  name: 'Rosemary Lemon Sharp',
  description: 'Rosmarin-Zitrone Drink für Fokus.',
  details: 'Rosmarin trifft Zitrone für klare Gedanken und Energie',
  category: 'focus',
  price: 15.99,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Erfrischend'],
  image: 'https://placehold.co/400x400/ADFF2F/ffffff?text=Rosemary+Lemon',
  gradient: ['#ADFF2F', '#32CD32'],
  featured: false,
  isNew: true
},
{
  id: 'blueberry-mint-mind',
  name: 'Blueberry Mint Mind',
  description: 'Heidelbeeren und Minze für mentale Klarheit.',
  details: 'Wilde Heidelbeeren mit frischer Minze für Fokus',
  category: 'focus',
  price: 16.49,
  size: '400g',
  servings: 20,
  features: ['Ohne Zucker', 'Vegan', 'Brain Food'],
  image: 'https://placehold.co/400x400/8A2BE2/ffffff?text=Blueberry+Mint',
  gradient: ['#8A2BE2', '#00FA9A'],
  featured: false,
  isNew: true
},
{
  id: "citrus-bomb",
  name: "Citrus Bomb",
  description: "Explosiver Zitrusmix für den ultimativen Frischekick.",
  details: "Eine spritzige Mischung aus Zitrone, Limette, Orange und Grapefruit für maximale Erfrischung",
  category: "basics",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FFA500/ffffff?text=Citrus+Bomb",
  gradient: ["#FFA500", "#FFD700"],
  featured: false,
  isNew: true
},
{
  id: "pink-life",
  name: "Pink Life",
  description: "Knalliger Mix aus Drachenfrucht und Granatapfel.",
  details: "Exotische Drachenfrucht kombiniert mit herben Granatapfel und Himbeere für einen fruchtigen Genuss",
  category: "basics",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FF69B4/ffffff?text=Pink+Life",
  gradient: ["#FF69B4", "#FF1493"],
  featured: false,
  isNew: true
},
{
  id: "dragonfruit-pomegranate",
  name: "Dragonfruit Pomegranate",
  description: "Exotischer Mix aus Drachenfrucht und Granatapfel.",
  details: "Fruchtige Drachenfrucht trifft auf herben Granatapfel für ein Geschmackserlebnis.",
  category: "basics",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FF69B4/ffffff?text=Dragonfruit+Pomegranate",
  gradient: ["#FF69B4", "#FF1493"],
  featured: false,
  isNew: true
},
{
  id: "starfruit-lime",
  name: "Starfruit Lime",
  description: "Erfrischender Sternfrucht-Limetten Drink.",
  details: "Exotische Sternfrucht kombiniert mit spritziger Limette für einen einzigartigen Geschmack",
  category: "basics",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FFFF66/000000?text=Starfruit+Lime",
  gradient: ["#FFFF66", "#ADFF2F"],
  featured: false,
  isNew: true
},
// === NEUE HINZUGEFÜGTE SORTEN ===
{
  id: "cherry-lime-splash",
  name: "Cherry Lime Splash",
  description: "Fruchtig-spritziger Mix aus Kirsche und Limette – perfekte Sommer-Vibes.",
  details: "Süße Kirsche trifft spritzige Limette; leicht säuerlich, erfrischend.",
  category: "basics",
  price: 13.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FF4D6D/ffffff?text=Cherry+Lime",
  gradient: ["#FF4D6D", "#FFD166"],
  featured: false,
  isNew: true
},
{
  id: "apple-pear-twist",
  name: "Apple Pear Twist",
  description: "Apfel trifft Birne mit einem feinen Twist — Herbstlich und clean.",
  details: "Milder Apfel, saftige Birne, dezente blumige Note.",
  category: "basics",
  price: 13.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliches Aroma"],
  image: "https://placehold.co/400x400/A3E635/ffffff?text=Apple+Pear",
  gradient: ["#A3E635", "#FCD34D"],
  featured: false,
  isNew: true
},
{
  id: "raspberry-peach-fizz",
  name: "Raspberry Peach Fizz",
  description: "Pfirsich und Himbeere mit sanftem Sprudelgefühl – Sommer im Glas.",
  details: "Süßer Pfirsich, frische Himbeere, leicht prickelnd.",
  category: "basics",
  price: 13.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Erfrischend"],
  image: "https://placehold.co/400x400/EC4899/ffffff?text=Raspberry+Peach",
  gradient: ["#EC4899", "#F59E0B"],
  featured: false,
  isNew: true
},
{
  id: "guarana-rush",
  name: "Guarana Rush",
  description: "Natürlicher Energy-Boost mit Guarana und Acerola — power ohne Crash.",
  details: "Guarana-Extrakt, Acerola für Vitamin C, leicht fruchtig.",
  category: "vitality",
  price: 15.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Mit natürlichem Koffein", "Vegan"],
  image: "https://placehold.co/400x400/F97316/ffffff?text=Guarana+Rush",
  gradient: ["#F97316", "#FACC15"],
  featured: true,
  isNew: true
},
{
  id: "aloe-lime-balance",
  name: "Aloe Lime Balance",
  description: "Aloe Vera trifft Zitrus — leicht, frisch und magenfreundlich.",
  details: "Aloe-Vera-Extrakt, Limette und Minze; sehr mild und erfrischend.",
  category: "wellness",
  price: 14.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Sanft für den Magen"],
  image: "https://placehold.co/400x400/86EFAC/ffffff?text=Aloe+Lime",
  gradient: ["#86EFAC", "#A7F3D0"],
  featured: false,
  isNew: true
},
{
  id: "berry-defense",
  name: "Berry Defense",
  description: "Cranberry, Acerola und Hibiskus — Immun- und antioxidantsupport.",
  details: "Säuerlich-fruchtiger Mix mit hohem Vitamin-C-Gehalt.",
  category: "wellness",
  price: 15.49,
  size: "400g",
  servings: 20,
  features: ["Mit Vitamin C", "Ohne Zucker", "Vegan"],
  image: "https://placehold.co/400x400/BE185D/ffffff?text=Berry+Defense",
  gradient: ["#BE185D", "#F43F5E"],
  featured: false,
  isNew: true
},
{
  id: "citrus-guayusa",
  name: "Citrus Guayusa",
  description: "Natürlicher Koffein-Kick aus Guayusa mit frischer Limette.",
  details: "Guayusa-Extrakt liefert sanftes Koffein; Limette sorgt für Frische.",
  category: "focus",
  price: 16.49,
  size: "400g",
  servings: 20,
  features: ["Mit natürlichem Koffein", "Ohne Zucker", "Vegan"],
  image: "https://placehold.co/400x400/FACC15/ffffff?text=Guayusa",
  gradient: ["#FACC15", "#4ADE80"],
  featured: true,
  isNew: true
},
{
  id: "pineapple-basil",
  name: "Pineapple Basil",
  description: "Süße Ananas trifft frisches Basilikum — exotisch, aber erwachsen.",
  details: "Reife Ananas, frische Basilikum-Blätter, leichte Säure der Limette.",
  category: "exotic",
  price: 14.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Exotisch"],
  image: "https://placehold.co/400x400/FCD34D/ffffff?text=Pineapple+Basil",
  gradient: ["#FCD34D", "#4ADE80"],
  featured: false,
  isNew: true
},
{
  id: "lychee-hibiscus",
  name: "Lychee Hibiscus",
  description: "Lychee trifft Hibiskus — blumig-exotisch und erfrischend.",
  details: "Zarte Lychee-Note, floraler Hibiskus und ein Hauch Zitrone.",
  category: "exotic",
  price: 15.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FB7185/ffffff?text=Lychee+Hibiscus",
  gradient: ["#FB7185", "#F9A8D4"],
  featured: false,
  isNew: true
},
{
  id: "frosted-berry-punch",
  name: "Frosted Berry Punch",
  description: "Winterlicher Mix aus Preiselbeeren und Minze — kühl und fruchtig.",
  details: "Preiselbeeren, Cranberry, Minze; ideal für kalte Tage und Feiertage.",
  category: "seasonal",
  price: 14.99,
  size: "400g",
  servings: 20,
  features: ["Limited Edition", "Ohne Zucker", "Vegan"],
  image: "https://placehold.co/400x400/93C5FD/ffffff?text=Frosted+Berry",
  gradient: ["#93C5FD", "#BE185D"],
  featured: false,
  isNew: true
},
{
  id: "citrus-defense-plus",
  name: "Citrus Defense+",
  description: "Orange, Grapefruit, Vitamin C und Zink — Immun-Boost im Glas.",
  details: "Hoher Vitamin-C-Anteil, Zink-Boost, natürliche Zitrus-Noten.",
  category: "immunity",
  price: 16.49,
  size: "400g",
  servings: 20,
  features: ["Mit Vitamin C", "Mit Zink", "Ohne Zucker", "Vegan"],
  image: "https://placehold.co/400x400/FBBF24/ffffff?text=Citrus+Defense",
  gradient: ["#FBBF24", "#F59E0B"],
  featured: false,
  isNew: true
},
{
  id: "honey-lemon-boost",
  name: "Honey Lemon Boost",
  description: "Honiggeschmack trifft Zitrone und Propolis — natürlich süßer Immunkick.",
  details: "Honig-Aroma, Zitrone, Propolis-Note; sanft und wohltuend.",
  category: "immunity",
  price: 15.99,
  size: "400g",
  servings: 20,
  features: ["Mit Propolis-Aroma", "Ohne Zuckerzusatz", "Vegan"],
  image: "https://placehold.co/400x400/FDE68A/000000?text=Honey+Lemon",
  gradient: ["#FDE68A", "#FACC15"],
  featured: false,
  isNew: true
},
// === ZUSÄTZLICHE SORTEN ===
{
  id: "pear-ginger-zest",
  name: "Pear Ginger Zest",
  description: "Birne trifft Ingwer mit frischem Zitrus-Kick.",
  details: "Saftige Birne mit leicht scharfem Ingwer und einem Hauch Zitrone",
  category: "basics",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/ADEFD1/000000?text=Pear+Ginger",
  gradient: ["#ADEFD1", "#A3E635"],
  featured: false,
  isNew: true
},
{
  id: "mango-lemon-splash",
  name: "Mango Lemon Splash",
  description: "Fruchtig-süßer Mango-Drink mit zitronigem Twist.",
  details: "Reife Mango mit frischer Zitrone, erfrischend und sommerlich",
  category: "basics",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FFD166/000000?text=Mango+Lemon",
  gradient: ["#FFD166", "#FFB347"],
  featured: false,
  isNew: true
},
{
  id: "yerba-energy",
  name: "Yerba Energy",
  description: "Natürlicher Energy-Drink mit Yerba Mate und Beeren.",
  details: "Yerba Mate, Goji und Himbeere für sanfte Power und Fokus",
  category: "vitality",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Mit natürlichem Koffein", "Vegan"],
  image: "https://placehold.co/400x400/32CD32/ffffff?text=Yerba+Energy",
  gradient: ["#32CD32", "#00FA9A"],
  featured: false,
  isNew: true
},
{
  id: "pineapple-ginger-charge",
  name: "Pineapple Ginger Charge",
  description: "Süße Ananas mit scharfem Ingwer-Kick.",
  details: "Saftige Ananas trifft leichten Ingwer für Energie und Frische",
  category: "vitality",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Mit Ingwer", "Vegan"],
  image: "https://placehold.co/400x400/FFD700/ffffff?text=Pineapple+Ginger",
  gradient: ["#FFD700", "#FFA500"],
  featured: false,
  isNew: true
},
{
  id: "cucumber-aloe-calm",
  name: "Cucumber Aloe Calm",
  description: "Erfrischender Wellness-Drink mit Gurke und Aloe.",
  details: "Gurke und Aloe Vera für sanfte Balance und Hydration",
  category: "wellness",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Erfrischend"],
  image: "https://placehold.co/400x400/98FB98/000000?text=Cucumber+Aloe",
  gradient: ["#98FB98", "#86EFAC"],
  featured: false,
  isNew: true
},
{
  id: "lime-ginseng-focus",
  name: "Lime Ginseng Focus",
  description: "Zitronen-Limetten Drink mit Ginseng für Fokus.",
  details: "Frische Limette trifft Ginseng und leichte Süße für mentale Klarheit",
  category: "focus",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Mit Ginseng", "Vegan"],
  image: "https://placehold.co/400x400/ADFF2F/000000?text=Lime+Ginseng",
  gradient: ["#ADFF2F", "#32CD32"],
  featured: false,
  isNew: true
},
{
  id: "passion-chili-lime",
  name: "Passion Chili Lime",
  description: "Exotischer Mix aus Passionsfrucht, Chili und Limette.",
  details: "Süß, fruchtig, leicht scharf – Abenteuer im Glas",
  category: "exotic",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Exotisch"],
  image: "https://placehold.co/400x400/FF6B6B/ffffff?text=Passion+Chili",
  gradient: ["#FF6B6B", "#FF4500"],
  featured: false,
  isNew: true
},
{
  id: "lemon-acerola-defense",
  name: "Lemon Acerola Defense",
  description: "Vitamin-C-Drink für extra Immunität.",
  details: "Zitrone und Acerola mit sanfter Süße, Immun-Boost inklusive",
  category: "immunity",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Mit Vitamin C", "Ohne Zucker", "Vegan"],
  image: "https://placehold.co/400x400/FCD34D/000000?text=Lemon+Acerola",
  gradient: ["#FCD34D", "#FFD700"],
  featured: false,
  isNew: true
},
{
   id: "christmas-spice-punch",
   name: "Christmas Spice Punch",
   description: "Wärmender Winterdrink mit Zimt, Nelke und Orange.",
   details: "Festliche Gewürze kombiniert mit fruchtiger Orange für gemütliche Momente",
   category: "seasonal",
   price: 15.49,
   size: "400g",
   servings: 20,
   features: ["Limited Edition", "Ohne Zucker", "Vegan"],
   image: "https://placehold.co/400x400/DC2626/ffffff?text=Christmas+Spice",
   gradient: ["#DC2626", "#FBBF24"],
   featured: false,
   isNew: true
},
{
  id: "nikos-taste",
  name: "Nikos Taste",
  description: "Einzigartiger Mix aus Mandarine und leichter Walnussnote. Erinnert an den Nikolaus (Wie der Name schon sagt).",
  details: "Saftige Mandarine kombiniert mit einem Hauch von Walnuss für ein besonderes Geschmackserlebnis. Verfeinert mit einem Hauch Kakao.",
  category: "basics",
  price: 14.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen", "Exklusiv"],
  image: "https://placehold.co/400x400/FFA500/ffffff?text=Nikos+Taste",
  gradient: ["#FFA500", "#FFD700"],
  featured: true,
  isNew: true
},
{
  id: "firework",
  name: "Firework",
  description: "Ein explosiver Mix aus allem, was man sich vorstellen kann. Zitrone, Orange, Limette, Grapefruit, Ananas, Mango, Maracuja, Kirsche, Himbeere, Erdbeere, Blaubeere, Brombeere und ein Hauch von Minze.",
  details: "Ein Feuerwerk der Aromen im Glas. Perfekt für alle, die es bunt und abwechslungsreich mögen.",
  category: "exotic",
  price: 16.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen", "Exklusiv", "Jahresend-Edition"],
  image: "https://placehold.co/400x400/FF4500/ffffff?text=Firework",
  gradient: ["#FF4500", "#FF69B4"],
  featured: true,
  isNew: true
},
{
  id: "study-buddy",
  name: "Study Buddy",
  description: "Der perfekte Begleiter für lange Lernnächte. Mit Guarana, Ginkgo und einem Hauch Zitrus für Fokus und Energie.",
  details: "Guarana-Extrakt für natürlichen Koffein-Kick, Ginkgo zur Unterstützung der Konzentration, verfeinert mit frischer Zitrone und Limette.",
  category: "focus",
  price: 16.49,
  size: "400g",
  servings: 20,
  features: ["Mit natürlichem Koffein", "Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/4B0082/ffffff?text=Study+Buddy",
  gradient: ["#4B0082", "#8A2BE2"],
  featured: true,
  isNew: true
},
{
  id: "holiday-glow",
  name: "Holiday Glow",
  description: "Ein festlicher Drink mit Cranberry, Orange und einem Hauch Zimt. Perfekt für die besinnliche Jahreszeit.",
  details: "Cranberry-Saft kombiniert mit fruchtiger Orange und einer Prise Zimt für ein wärmendes Geschmackserlebnis.",
  category: "seasonal",
  price: 15.99,
  size: "400g",
  servings: 20,
  features: ["Limited Edition", "Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/DC143C/ffffff?text=Holiday+Glow",
  gradient: ["#DC143C", "#FF4500"],
  featured: true,
  isNew: true
},
{
  id: "tropical-turmeric",
  name: "Tropical Turmeric",
  description: "Ein exotischer Mix aus Ananas, Mango und Kurkuma für einen gesunden Start in den Tag.",
  details: "Saftige Ananas und Mango kombiniert mit der wohltuenden Wirkung von Kurkuma und einem Hauch Ingwer.",
  category: "wellness",
  price: 15.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen", "Entzündungshemmend"],
  image: "https://placehold.co/400x400/FFA500/ffffff?text=Tropical+Turmeric",
  gradient: ["#FFA500", "#FFD700"],
  featured: true,
  isNew: true
},
{
  id: "blue series",
  name: "Blue Series",
  description: "Ein fruchtig süßer Mix aus blauen Früchten wie Blaubeere, Holunder und schwarzer Johannisbeere.",
  details: "Blaubeeren, Holunderbeeren und schwarze Johannisbeeren vereinen sich zu einem intensiven Geschmackserlebnis mit natürlicher Süße.",
  category: "basics",
  price: 14.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/0000FF/ffffff?text=Blue+Series",
  gradient: ["#0000FF", "#4B0082"],
  featured: false,
  isNew: true
},
{
  id: "rainbow-refresh",
  name: "Rainbow Refresh",
  description: "Ein bunter Mix aus verschiedenen Früchten für den ultimativen Frischekick.",
  details: "Eine Kombination aus Zitrusfrüchten, Beeren und tropischen Früchten für ein erfrischendes Geschmackserlebnis.",
  category: "exotic",
  price: 16.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FF69B4/ffffff?text=Rainbow+Refresh",
  gradient: ["#FF69B4", "#FFD700"],
  featured: false,
  isNew: true
},
// === ADDITIONAL FLAVORS ===
{
  id: "apple-cinnamon",
  name: "Apple Cinnamon",
  description: "Klassisch wärmend: Apfel mit Zimt und Vanille.",
  details: "Frische Äpfel trifft wärmende Gewürze für Herbst und Winter",
  category: "basics",
  price: 12.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/CD853F/ffffff?text=Apple+Cinnamon",
  gradient: ["#CD853F", "#FFB347"],
  featured: false,
  isNew: false
},
{
  id: "blueberry-pomegranate",
  name: "Blueberry Pomegranate",
  description: "Antioxidantien-Power: Blaubeeren mit Granatapfel.",
  details: "Zwei Superfrüchte kombiniert für maximale Gesundheitsvorteile",
  category: "wellness",
  price: 15.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Antioxidantien", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/800080/ffffff?text=Blueberry+Pomegranate",
  gradient: ["#800080", "#FF1493"],
  featured: false,
  isNew: false
},
{
  id: "mango-cardamom",
  name: "Mango Cardamom",
  description: "Tropische Mango trifft orientalisches Kardamom.",
  details: "Süße Mango verfeinert mit exotischem Kardamom-Aroma",
  category: "exotic",
  price: 15.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FFB347/ffffff?text=Mango+Cardamom",
  gradient: ["#FFB347", "#FF8C00"],
  featured: false,
  isNew: false
},
{
  id: "raspberry-hibiscus",
  name: "Raspberry Hibiscus",
  description: "Himbeere mit Hibiskus für blumig-fruchtiges Aroma.",
  details: "Süßliche Himbeeren trifft auf florales Hibiskus für Wellness-Drink",
  category: "wellness",
  price: 14.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FF69B4/ffffff?text=Raspberry+Hibiscus",
  gradient: ["#FF69B4", "#DC143C"],
  featured: false,
  isNew: false
},
{
  id: "pineapple-lime",
  name: "Pineapple Lime",
  description: "Ananas mit Limette für tropische Frische.",
  details: "Saftige Ananas mit säuerlicher Limette für erfrischenden Kick",
  category: "basics",
  price: 12.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FFFF00/ffffff?text=Pineapple+Lime",
  gradient: ["#FFFF00", "#00FF00"],
  featured: false,
  isNew: false
},
{
  id: "cherry-almond",
  name: "Cherry Almond",
  description: "Süßkirsche mit zartem Mandelton.",
  details: "Saftige Kirsche kombiniert mit cremigem Mandelaroma",
  category: "basics",
  price: 13.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/DC143C/ffffff?text=Cherry+Almond",
  gradient: ["#DC143C", "#FFB347"],
  featured: false,
  isNew: false
},
{
  id: "orange-vanilla",
  name: "Orange Vanilla",
  description: "Klassisch cremig: Orange mit Vanille.",
  details: "Frische Orange verfeinert mit zartem Vanilla-Hauch",
  category: "basics",
  price: 13.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FFA500/ffffff?text=Orange+Vanilla",
  gradient: ["#FFA500", "#FFFACD"],
  featured: false,
  isNew: false
},
{
  id: "guava-papaya",
  name: "Guava Papaya",
  description: "Exotisches Duo aus Guave und Papaya.",
  details: "Zwei tropische Früchte für authentisches Urlaubsgefühl",
  category: "exotic",
  price: 14.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FFD700/ffffff?text=Guava+Papaya",
  gradient: ["#FFD700", "#FF8C00"],
  featured: false,
  isNew: false
},
{
  id: "blackcurrant-mint",
  name: "Blackcurrant Mint",
  description: "Schwarze Johannisbeere mit erfrischender Minze.",
  details: "Intensive Schwarze Johannisbeere gekühlt durch Minze",
  category: "basics",
  price: 13.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen", "Minze"],
  image: "https://placehold.co/400x400/1C1C1C/ffffff?text=Blackcurrant+Mint",
  gradient: ["#1C1C1C", "#800080"],
  featured: false,
  isNew: false
},
{
  id: "lavender-lemonade",
  name: "Lavender Lemonade",
  description: "Beruhigende Lavendel mit klassischem Zitronengeschmack.",
  details: "Florales Lavendel trifft auf erfrischende Zitrone",
  category: "relax",
  price: 14.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen", "Beruhigend"],
  image: "https://placehold.co/400x400/E6E6FA/ffffff?text=Lavender+Lemonade",
  gradient: ["#E6E6FA", "#FFD700"],
  featured: false,
  isNew: false
},
{
  id: "dragon-fruit-lime",
  name: "Dragon Fruit Lime",
  description: "Pink Pitahaya mit säuerlicher Limette.",
  details: "Exotische Drachenfrucht mit punchy Limetten-Note",
  category: "exotic",
  price: 15.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/FF69B4/ffffff?text=Dragon+Fruit+Lime",
  gradient: ["#FF69B4", "#00FF00"],
  featured: false,
  isNew: false
},
{
  id: "matcha-coconut",
  name: "Matcha Coconut",
  description: "Grüner Matcha mit cremiger Kokosnuss.",
  details: "Antioxidant-reicher Matcha kombiniert mit Kokosnuss-Cremigkeit",
  category: "focus",
  price: 16.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen", "Energie"],
  image: "https://placehold.co/400x400/228B22/ffffff?text=Matcha+Coconut",
  gradient: ["#228B22", "#FFFACD"],
  featured: true,
  isNew: true
},
{
  id: "acai-berry-mix",
  name: "Acai Berry Mix",
  description: "Superfood Acai mit Beeren-Mix.",
  details: "Powerbeere Acai mit Blaubeeren, Himbeeren und Brombeeren",
  category: "wellness",
  price: 17.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Superfood", "Antioxidantien"],
  image: "https://placehold.co/400x400/800080/ffffff?text=Acai+Berry+Mix",
  gradient: ["#800080", "#FF1493"],
  featured: true,
  isNew: true
},
{
  id: "kiwi-strawberry",
  name: "Kiwi Strawberry",
  description: "Exotische Kiwi mit heimischer Erdbeere.",
  details: "Grüne Kiwi trifft auf rote Erdbeere für fruchtigen Mix",
  category: "basics",
  price: 13.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Mit Vitamin C"],
  image: "https://placehold.co/400x400/98FB98/ffffff?text=Kiwi+Strawberry",
  gradient: ["#98FB98", "#FF69B4"],
  featured: false,
  isNew: false
},
{
  id: "pomegranate-elderflower",
  name: "Pomegranate Elderflower",
  description: "Intensiver Granatapfel mit zartem Holunderblüten-Aroma.",
  details: "Reichhaltige Granatapfel verfeinert durch florales Holunder",
  category: "wellness",
  price: 15.99,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Natürliche Aromen"],
  image: "https://placehold.co/400x400/DC143C/ffffff?text=Pomegranate+Elderflower",
  gradient: ["#DC143C", "#E6E6FA"],
  featured: false,
  isNew: false
},
{
  id: "mango-turmeric-ginger",
  name: "Mango Turmeric Ginger",
  description: "Golden Milk Variante: Mango mit Kurkuma und Ingwer.",
  details: "Süße Mango kombiniert mit Kurkuma und Ingwer für Wellness",
  category: "wellness",
  price: 16.49,
  size: "400g",
  servings: 20,
  features: ["Ohne Zucker", "Vegan", "Entzündungshemmend", "Ingwer"],
  image: "https://placehold.co/400x400/FFB347/ffffff?text=Mango+Turmeric",
  gradient: ["#FFB347", "#FF7F50"],
  featured: false,
  isNew: true
}
];
